### ISSUE TITLE
Failed to fetch error on occasion

### ISSUE THREAD

**Issue by mapnrd** [protomaps/PMTiles#384] opened 2024-04-11 18:44 UTC
I am hosting pmtiles on aws, rendering with pmtiles 3.0.5 + maplibre 4.1.2. The tiles work well, but on occasion will fail to load a map tile or at very least will throw  fetch and cache errors to the console. 

This is not generally a big deal, but it will seems to hang on that sometimes. Any help is greatly appreciated!

<img width="988" alt="pmtiles_cache_error" src="https://github.com/protomaps/PMTiles/assets/166751134/777867da-f97d-4006-8282-9f3d79c3a91b">

**Comment by bdon** [comment] 2024-04-14 14:46
is this Chrome browser on windows? There are no tiles that fail to load that actually appear, right? When zooming there is many tile requests that are cancelled immediately and never make it to the screen, so it may be a benign error message, but worth investigating more.

**Comment by Sidders22** [comment] 2024-04-14 16:54
Commenting here to add I experience the same thing on Chrome, but my PMTiles file is hosted locally and rendered with OpenLayers.

**Comment by bdon** [comment] 2024-09-12 15:54
I'm going to close this as a duplicate of #442 which has more information.

**Closed by bdon** 2024-09-12 15:54 UTC

**Comment by bdon** [comment] 2024-09-14 04:38
@mapnrd @Sidders22 can you confirm that you're using Chrome on Windows?

Potential workaround described in https://github.com/protomaps/PMTiles/issues/442#issuecomment-2347943421

**Comment by bdon** [comment] 2024-09-19 15:34
Workaround is implemented in pmtiles 3.1.0 / ol-pmtiles 1.0.2.

**Comment by mapnrd** [comment] 2024-09-19 16:26
Yes, it is chrome on windows. On Sep 13, 2024, at 9:38 PM, Brandon Liu ***@***.***> wrote:﻿
@mapnrd @Sidders22 can you confirm that you're using Chrome on Windows?
Potential workaround described in #442 (comment)
