### ISSUE TITLE
AstroJS build error "Named export 'Protocol' not found."

### ISSUE THREAD

**Issue by tordans** [protomaps/PMTiles#248] opened 2023-09-04 19:13 UTC
For some reason, I imported `{ Protocol }` and not `* as pmtiles` (like this https://github.com/tordans/berlin-bikenetwork-monitoring/blob/0704fe8a517e75669154e1bf2a9e5ec0ca810da8/src/components/Map/Map.tsx#L3) in https://github.com/tordans/berlin-bikenetwork-monitoring (maybe I copied it from [this one place](https://github.com/search?q=repo%3Aprotomaps%2FPMTiles+%22new+Protocol%22&type=code)? IDK).

When I build this AstroJS project via `npm run build` I get the following error.

```
error   Named export 'Protocol' not found. The requested module 'pmtiles' is a CommonJS module, which may not support all module.exports as named exports.
  CommonJS modules can always be imported via the default export, for example using:

  import pkg from 'pmtiles';
  const { Protocol } = pkg;

file:///Users/…/berlin-bikenetwork-monitoring/dist/chunks/pages/index.astro.fa247295.mjs:6
import { Protocol } from 'pmtiles';
         ^^^^^^^^
SyntaxError: Named export 'Protocol' not found. The requested module 'pmtiles' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'pmtiles';
const { Protocol } = pkg;

    at ModuleJob._instantiate (node:internal/modules/esm/module_job:124:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:190:5)
```

---

When I do the suggested change, I get…

```
"default" is not exported by "node_modules/pmtiles/dist/index.mjs", imported by "src/components/Map/Map.tsx".
file: /Users/…/berlin-bikenetwork-monitoring/src/components/Map/Map.tsx:3:7
1: import maplibregl from 'maplibre-gl'
2: import 'maplibre-gl/dist/maplibre-gl.css'
3: import pmtiles from 'pmtiles'
          ^
4: import { useEffect } from 'react'
5: import ReactMapGl, { NavigationControl } from 'react-map-gl/dist/es5/exports-maplibre.js'
```

----

The solution is, to do [as the docs say](https://github.com/protomaps/PMTiles/blob/main/js/README.md?plain=1#L12) and use ` import * as pmtiles from "pmtiles";`.

However, using this way of importing always feels like an error. And there should be a way to allow for the other syntax as well, right?

**Comment by bdon** [comment] 2023-09-11 02:11
Yes, that syntax (named imports) ought to be supported, if it isn't we need to make the change in a major (breaking) version of the JS. 

But something also seems funny about
```
import { Protocol } from 'pmtiles';
```

I do named imports here: https://github.com/protomaps/protomaps-leaflet/blob/main/src/tilecache.ts#L4

Your builder system should use the ES6 module version of the package in `dist/` https://unpkg.com/browse/pmtiles@2.10.0/dist/ and not the CommonJS one (`.cjs`) - I'm not familiar with Astro however

**Comment by tordans** [comment] 2024-01-27 06:12
I updated to the lastest AstroJS which uses Vite5 … and did a bunch of other stuff … and now the issue is gone.
Commit https://github.com/tordans/berlin-bikenetwork-monitoring/commit/85d7a1617f5a44f7605691a3d47a2a6765bf40b2

---

I also use those TS Package checkers which do not show any relevant (I think) issues. So I am closing this …

- https://arethetypeswrong.github.io/?p=pmtiles%402.11.0 no issues
- https://publint.dev/pmtiles@2.11.0 some notices about improvements but I don't think they are super important …

**Comment by tordans** [comment] 2024-01-27 06:19
Sorry, this was not solved … I failed to remember _again_ that Vite "local dev" is something completely different from Vite "build" (cannot wait for the Rust port that will finally fix this …).

```
Named export 'Protocol' not found. The requested module 'pmtiles' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'pmtiles';
const { Protocol } = pkg;

  Stack trace:
    at ModuleJob._instantiate (node:internal/modules/esm/module_job:[123](https://github.com/tordans/berlin-bikenetwork-monitoring/actions/runs/7676858149/job/20924907050#step:3:129):21)
    at async ModuleLoader.import (node:internal/modules/esm/loader:336:24)
    at async generatePages (file:///home/runner/work/berlin-bikenetwork-monitoring/berlin-bikenetwork-monitoring/node_modules/astro/dist/core/build/generate.js:164:9)
    at async AstroBuilder.build (file:///home/runner/work/berlin-bikenetwork-monitoring/berlin-bikenetwork-monitoring/node_modules/astro/dist/core/build/index.js:138:5)
    at async build (file:///home/runner/work/berlin-bikenetwork-monitoring/berlin-bikenetwork-monitoring/node_modules/astro/dist/core/build/index.js:47:3)
Error: Process completed with exit code 1.
```

**Comment by tordans** [comment] 2024-01-27 06:30
@bdon I managed to get "npm run build" working with Vite/AstroJS after modifying the package.json locally like this https://github.com/protomaps/PMTiles/pull/329

Maybe this is something you can use to fix the package building pipeline.

**Comment by bdon** [comment] 2024-01-27 12:07
Can you create a minimal Astro project from scratch, with only the `pmtiles` package added as a dependency (no maplibre, etc) and a component that loads it, and upload it here?

**Comment by bdon** [comment] 2024-01-29 10:04
@tordans please try js 3.0.0-alpha.0, should fix issue with named exports.

**Comment by bdon** [comment] 2024-01-31 04:47
marking this as duplicate of #317 , please continue discussion there

**Closed by bdon** 2024-01-31 04:47 UTC
