### ISSUE TITLE
pmtiles in SSR in sveltekit v2, vite 5, Astro (ES6 module problems)

### ISSUE THREAD

**Issue by JinIgarashi** [protomaps/PMTiles#317] opened 2024-01-04 16:28 UTC
I upgraded sveltekit to v2, then faced an issue of importing pmtiles in SSR in sveltekit v2 and vite5. The following error log was generated by vite when I built source code.

```
3:24:16 PM [vite] Error when evaluating SSR module /src/routes/+layout.server.ts: failed to import "/src/lib/server/helpers/index.ts"
|- SyntaxError: [vite] Named export 'PMTiles' not found. The requested module 'pmtiles' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'pmtiles';
const {PMTiles} = pkg;
```

But changing to the example suggested by the error does not solve the issue. I was really struggling to fix it, but somehow I managed to fix the issue to add `pmtiles` into `ssr.noExternal` at vite.config.ts as following example.

```ts
import { defineConfig } from 'vite'

export default defineConfig({
  plugins: [sveltekit()],
  ssr: {
    noExternal: [ 'pmtiles', 'maplibre-gl']
  }
})
```

after adding the above setting, works without changing. maplibre-gl also has same issue of importing at SSR, it also needs to be added to ssr.noExternal config.

I am not sure how many users use pmtiles in sveltekit, I wanted to share my solution with the community for future reference. This is a tricky issue.

**Comment by bdon** [comment] 2024-01-15 09:23
Thanks for the report, let's leave this open to help others with the issue and work on making a reproducible example with sveltekit2+vite5

**Comment by Havegum** [comment] 2024-01-25 14:53
Here's a minimal sveltekit project that demonstrates the strange import behaviour:
https://github.com/Havegum/pmtiles-sveltekit-bug

It seems to load differently in dev mode compared to at build time.

In dev mode, you can import the exported classes like this:
```js
import * as pmtiles from "pmtiles";
const { PMTiles } = pmtiles;
```

At build time, I've gotten a hold of the exported classes like so:
```js
import * as pmtiles from "pmtiles";
const { PMTiles } = pmtiles.default;
```

The build time syntax seems to imply that you could just import default from `pmtiles` directly, but then it complains in dev mode that `pmtiles` _has_ no default export 🤷 

### Workaround

For now, I get around this with the nullish coalescing operator:
```js
import * as pmtiles from "pmtiles";
const { PMTiles } = pmtiles.default ?? pmtiles;
```

**Comment by bdon** [comment] 2024-01-27 12:34
@Havegum thanks for the perfect reproduction example! opened PR #330

**Comment by bdon** [comment] 2024-01-29 10:03
@Havegum @JinIgarashi please try JS version 3.0.0-alpha.0, named exports should work out of the box now.

**Comment by JinIgarashi** [comment] 2024-01-29 10:25
@bdon thanks, I will test this alpha version

**Comment by Havegum** [comment] 2024-01-30 08:54
It works brilliantly – for me at least! Thank you for the swift fix! ✨

**Comment by bdon** [comment] 2024-01-31 06:30
js 3.0.0-alpha.1 published, with MapLibre GL JS v4.x support

**Comment by JinIgarashi** [comment] 2024-01-31 14:03
@bdon I just confirmed pmtiles alpha.1 can work with SSR in sveltekit without additional setting in vite.config.ts

maplibre also has same issue, I need to `maplibregl.addProtocal` inside onMount method of svelte. but this is issue for maplibre, not an issue of pmtiles.

I believe if maplibre will do same fixes of pmtiles, `addProtocal` can also work outside of onMount.

```svelte
<script lang="ts">
	import maplibregl from 'maplibre-gl';
	import * as pmtiles from 'pmtiles';
	import { onMount } from 'svelte';

	onMount(() => {
		let protocol = new pmtiles.Protocol();
		maplibregl.addProtocol('pmtiles', protocol.tile);		
	});
</script>
```

vite.config.ts setting for maplibre.

```ts
import { sveltekit } from '@sveltejs/kit/vite';
import { defineConfig } from 'vite';

export default defineConfig({
	plugins: [sveltekit()],
	ssr: {
		noExternal: 'maplibre-gl'
	}
});

```

**Comment by bdon** [comment] 2024-02-01 03:07
@JinIgarashi @tordans @Havegum can you confirm that TypeScript types are included? in 3.0.0-alpha.2? Publint is flagging it as a potential issue: https://publint.dev/pmtiles@3.0.0-alpha.2

**Comment by Havegum** [comment] 2024-02-02 08:45
I'm getting types and everything, yes – but I'm not using `"moduleResolution": "bundler"`.

If I understand [these hints](https://publint.dev/rules#types_not_exported) from the same page, renaming the `.d.ts`-file to have a `.d.mts` extension should resolve that issue.

**Comment by bdon** [comment] 2024-02-02 09:48
Unfortunately I think the way the TypeScript types are emitted is incompatible the way the ESM module is bundled right now. I'm going to publish v3.0.0 now, since MapLibre 4.0.0 has been published and the current `latest` pmtiles tag is incompatible with that. So any restructuring of ESM like non-bundling will have to wait until a later version, it seems like the current types configuration is working for most people.

**Comment by bdon** [comment] 2024-02-02 10:50
3.0.0 released, marking as resolved, please open a new issue for any packaging related problems.

**Closed by bdon** 2024-02-02 10:50 UTC
