### ISSUE TITLE
Improving performance? GitHub hosting.

### ISSUE THREAD

**Issue by KoalaGeo** [protomaps/PMTiles#264] opened 2023-10-04 12:56 UTC
Hi, 

I'm investigating using pmtiles for some of our static / long update period datasets at the British Geological Survey. 

I've made a pmtiles file (~50MB) and added to GitHub - https://github.com/KoalaGeo/QGIS-Leaflet-Maps/blob/master/radon/radon_v2.pmtiles 

I'm then serving this at https://koalageo.rocks/QGIS-Leaflet-Maps/radon/radon-ol.html

However it seems to take 3 - 5 secs to render the tiles - much slower than connecting to say a WMTS. 

Is there any way I can optimise my file or openlayers so it draws faster? 

Many thanks

**Comment by bdon** [comment] 2023-10-04 13:02
Please provide some examples of slow requests on that page, here's what I see:

<img width="815" alt="Screenshot 2023-10-04 at 21 01 14" src="https://github.com/protomaps/PMTiles/assets/77501/2f217603-d502-4e27-81fc-7fe0321a9af4">

Those response times look typical for GH pages; you have a 2.8 MB tile which is unusually large.

**Comment by KoalaGeo** [comment] 2023-10-04 15:51
Thanks for checking: I can get 12.03 s for the 2.8 MB tile:

![image](https://github.com/protomaps/PMTiles/assets/33657876/7308cfc7-4602-4f52-a980-c92399b238c2)

Counting while https://koalageo.rocks/QGIS-Leaflet-Maps/radon/radon-ol.html loads and renders can take >12 sec

It's faster using the pmtiles viewer - https://protomaps.github.io/PMTiles/?url=https%3A%2F%2Fkoalageo.rocks%2FQGIS-Leaflet-Maps%2Fradon%2Fradon_v2.pmtiles#map=4.96/55.75/-2.82 

I made the vector tiles using QGIS to a mbtiles file (z 0 - 11), then converted to pmtiles. Any recommendations to make sure the tiles are smaller?

**Comment by bdon** [comment] 2023-10-05 03:10
Thanks for the additional info. Can you reproduce those 12 second responses when monitoring the network in the viewer you linked? https://protomaps.github.io/PMTiles/?url=https%3A%2F%2Fkoalageo.rocks%2FQGIS-Leaflet-Maps%2Fradon%2Fradon_v2.pmtiles#map=4.96/55.75/-2.82

What web browser are you using?

**Comment by bdon** [comment] 2023-10-20 19:33
I'm not able to reproduce the slow responses in Firefox 118.0.2 in Mac, though the experience of browsing the map is pretty slow for the given dataset - if your geometry is pure square pixels then a raster-based approach using COG may be a more efficient encoding (though you wouldn't be able to attach attributes to each pixel)

Additional useful information is these values that come back from GitHub pages:

`x-cache`, `x-served-by`

**Comment by bdon** [comment] 2024-01-30 07:51
It looks like this issue can be resolved by reducing the size of tiles, please re-open this if you are observing something different.

**Closed by bdon** 2024-01-30 07:51 UTC
