### ISSUE TITLE
OpenLayers Vector tiles example not working

### ISSUE THREAD

**Issue by luizpara** [protomaps/PMTiles#225] opened 2023-07-22 03:48 UTC
I am trying to test the official [OpenLayers example for Vector Tiles](https://github.com/protomaps/PMTiles/tree/main/openlayers).

After creating a new OpenLayers project the standard way and also after installing ol-pmtiles with `npm install ol-pmtiles`, I try running the official example by using the following two files.

index.html:
```
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>PMTiles OpenLayers Vector Example</title>
        <meta charset="utf-8"/>
        <script src="https://cdn.jsdelivr.net/npm/ol@v7.3.0/dist/ol.js"></script>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/ol@v7.3.0/ol.css">
        <style>
            body, #map {
                height:100vh;
                margin: 0;
            }
        </style>
    </head>
  <body>
    <div id="map"></div>
    <script type="module" src="./main.js"></script>
  </body>
</html>
```

main.js:
```
import "./style.css";
import { Map, View } from "ol";
import VectorTile from "ol/layer/VectorTile";
import { PMTilesVectorSource } from "ol-pmtiles";
import { Style, Stroke, Fill } from 'ol/style';
import { useGeographic } from 'ol/proj';

const vectorLayer = new VectorTile({
  declutter: true,
  source: new PMTilesVectorSource({
    url: "https://r2-public.protomaps.com/protomaps-sample-datasets/nz-buildings-v3.pmtiles",
    attributions: ["© Land Information New Zealand"],
  }),
  style: new Style({
    stroke: new Stroke({
      color: "gray",
      width: 1,
    }),
    fill: new Fill({
      color: "rgba(20,20,20,0.9)",
    }),
  }),
});

useGeographic();

const map = new Map({
  target: "map",
  layers: [vectorLayer],
  view: new View({
    center: [172.606201,-43.556510],
    zoom: 7,
  }),
});
```

However, the map doesn't get displayed. I see the zoom buttons in the top-left and the attribution icon in the bottom-right. But not the map. Inspecting the browser console, there are not errors and no warnings. I did try with different web browsers.

Perhaps interestingly, the official Raster Tile example-code in that same link works perfectly. I wonder if something has changed in the `ol-pmtiles` API that did not get updated in the Vector Tiles exampled?

**Comment by bdon** [comment] 2023-07-22 12:18
Are you able to see requests for `https://r2-public.protomaps.com/protomaps-sample-datasets/nz-buildings-v3.pmtiles` appearing in your network tab?

**Comment by luizpara** [comment] 2023-07-22 17:37
@bdon firstly, thank you for the quick follow-up! Yes I can see the requests, both when the page loads and when I try to zoom or pan (even if nothing is displayed).

**Comment by mir123** [comment] 2023-07-28 19:27
I'm trying to use OpenLayers with my own data and get the same symptoms, resource gets loaded, zooming and panning loads more data, but nothing gets displayed. I tried with my own data using the example at https://github.com/protomaps/PMTiles/blob/main/openlayers/examples/vector.html and it does work, so it could be something with the npm package?

**Comment by bdon** [comment] 2023-08-01 06:29
Hi, can you please upload a ZIP file somewhere of your entire application including the build system package.json, etc as well as your dataset? otherwise it is impossible to reproduce what is going on by guessing.

**Comment by devonbarrett** [comment] 2023-08-06 14:29
```js
 this.pmtiles_
        .getZxy(z, x, y)
        .then((tile_result) => {
          if (tile_result) {
            const format = tile.getFormat();
            tile.setFeatures(
              format.readFeatures(tile_result.data.buffer, {
```

` this.pmtiles_.getZxy(z, x, y)` returns an promise that results to an object with the shape of `{data: ArrayBuffer}`.

This means that `tile_result.data.buffer` is undefined, and no features are read. However, reading the features from `tile_result.data` works as expected.

https://github.com/protomaps/PMTiles/blob/main/openlayers/src/index.js#L59

**Comment by mir123** [comment] 2023-08-06 19:51
Hello Brandon, find zip file [here](https://drive.google.com/file/d/17Ge6YgbtrzQB6vg8ihLkRMDoEVjKukBX/view?usp=sharing)

This is made using [ol-vite](https://github.com/openlayers/ol-vite):

```
npx create-ol-app pmtiles-test --template vite
cd pmtiles-test
npm install ol-pmtiles
```

Then copying and pasting the OpenLayers example in main.js

**Comment by bdon** [comment] 2023-08-07 04:31
@devonbarrett thanks for tracking this down - looks like the pmtiles v2.7.2 inadvertently changed the return type from an ArrayBuffer to a typed array, so I've bumped that dependency to the latest and fixed this code

@mir123 @luizpara can you please try ol-pmtiles v0.1.1 https://www.npmjs.com/package/ol-pmtiles

Unfortunately because of the difficulties with OpenLayers and bundling/script includes described in #3 I have to maintain two hand-synced copies of the OL implementation in JS (not TS) right now - open to ideas for a better build

**Comment by mir123** [comment] 2023-08-07 19:14
Fantastic, same setup works now after upgrade to v0.1.1. Will test with my data now

**Comment by bdon** [comment] 2023-08-08 05:48
Great! I'll close this issue for now, thanks for your patience.

**Closed by bdon** 2023-08-08 05:48 UTC
